// GET SINGLE IMAGE FROM DATABASE
GET http://localhost:8080/api/files/5ed39b61be0d454cb87dfd4e

###
// POST A SINGLE IMAGE
POST http://localhost:8080/api/files
Content-Type: multipart/form-data; boundary=----WebKitFormBoundary7MA4YWxkTrZu0gW

------WebKitFormBoundary7MA4YWxkTrZu0gW
Content-Disposition: form-data; name="image"; filename="uggla.jpg"
Content-Type: image/jpeg

< ./uggla.jpg
------WebKitFormBoundary7MA4YWxkTrZu0gW--

###
// DELETE A SINGLE IMAGE
DELETE http://localhost:8080/api/files/5ed39901fc46de3ec04fabdd