
//GET ALL ORDERS
GET http://localhost:8080/api/orders

###

//GET ALL ORDERS FOR A USER
GET http://localhost:8080/api/orders/user/5ece3997cfd4241588e1a861

###

//GET ORDER BY ID
GET http://localhost:8080/api/orders/5ece4f164242374d7055567a

###

//POST ORDER
POST http://localhost:8080/api/orders
Content-Type: application/json

{
    "user" : {
        "_id" : "5ece3997cfd4241588e1a861",
        "email": "adam@gmail.se",
        "password": "123kjhsakjdh123",
        "firstName" : "Hans2",
        "lastName" : "Jansson",
        "phoneNumber" : "07007007070",
        "streetAddress" : "Hansons gata 1",
        "zipCode" : "12345",
        "city" : "Hjo",
        "isAdmin": false
    },
    "products" : [{
        "_id" : "5ece411c56e2613c4c3b0d44",
        "title": "fina produkten",
        "desc": "fin produkt",
        "image": "5ed6084e8eb04037a0db00b7",
        "price": "2",
        "category": "fina produkter",
        "sizes": [{
            "size": "small",
            "stock": "1"
        }]
    }],
    "toAddress" : "Tillgatan 20",
    "toZipCode" : "42024",
    "toCity" : "GOTHENBURG",
    "shippingMethod" : {
        "_id" : "5ece411c56e2613c4c3b0d45",
        "type" : "postpaket",
        "desc" : "leveranslotto",
        "company" : "postmord",
        "price" : "199",
        "deliveryTime" : "14"
    },
    "paymentMethod" : {
        "_id" : "5ece411c56e2613c4c3b0d46",
        "type" : "Klarna faktura",
        "desc" : "för man vet ju aldrig",
        "price" : "99"
    }
}

###

//UPDATE ORDER (Kommer denna användas?)
PUT http://localhost:8080/api/orders/orderId
Content-Type: application/json

{
    "toAddress" : "Nygatan 20",
    "toZipCode" : "420 24",
    "toCity" : "GOTHENBURG"
}