// GET ALL SHIPMENTS
GET http://localhost:8080/api/shipments

###

// POST A SHIPMENT

POST http://localhost:8080/api/shipments
Content-Type: application/json

{
    "type" : "Normal delivery",
    "desc" : "Delivery to your nearest postal office",
    "company" : "Postnord",
    "price" : "5",
    "deliveryTime" : "5"
}
{
    "type" : "Express delivery",
    "desc" : "Fast delivery to your nearest postal office",
    "company" : "DHL",
    "price" : "10",
    "deliveryTime" : "3"
}
{
    "type" : "Home delivery",
    "desc" : "Delivery to your front door",
    "company" : "DB Schenker",
    "price" : "15",
    "deliveryTime" : "2"
}