GET http://localhost:8080/api/users/all
###
GET http://localhost:8080/api/users/

###
POST http://localhost:8080/api/users/
Content-Type: application/json

{
    "email" : "nyuser@test.com",
    "password" : "hansonjansson",
    "firstName" : "Hans2",
    "lastName" : "Jansson",
    "phoneNumber" : "07007007070",
    "streetAddress" : "Hansons gata 1",
    "zipCode" : "12345",
    "city" : "Hjo",
    "isAdmin" : "true"
}

###
PUT http://localhost:8080/api/users/5ece2ad51c7670319c72aa32
Content-Type: application/json

{
    "email" : "Hej!@test.com",
    "password" : "hejehjehe",
    "firstName" : "Hans",
    "lastName" : "Jansson",
    "phoneNumber" : "07007007070",
    "streetAddress" : "Hansons gata 1",
    "zipCode" : "12345",
    "city" : "Hjo",
    "isAdmin" : "false"
}

###
DELETE http://localhost:8080/api/users/5ece226d487c2c16044957f7

###
POST http://localhost:8080/api/users/session/login/
Content-Type: application/json

{
    "email" : "admin@admin.com",
    "password" : "hansonjansson"
}

###
DELETE http://localhost:8080/api/users/session/logout/